version: '3'

services:
  student-service:
    build:
      context: ./student-service
      dockerfile: Dockerfile
    container_name: student-service
    ports:
      - "8082:8080"
    environment:
      - RUST_LOG=info
      - DATABASE_URL=postgres://postgres:postgrespassword@postgres:5432/students
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_VHOST=/
    networks:
      - microservices-network

networks:
  microservices-network:
    external: true